### ISSUE TITLE
updating texture list when removing texture

### ISSUE THREAD

**Issue by andrea-bistacchi** [andrea-bistacchi/PZero#25]
When a texture is removed, its name is not immediately removed from the list of textures appearing for each DEM in the view DEM & DOM list. This is probably related to a missing signal in the remove texture function.

We must also verify if textures are automatically removed from DEMs when the underlying image is removed from the project.

**Comment by gbene** [comment]
Fixed in https://github.com/andrea-bistacchi/PZero/commit/855a76d60c03711c32af52d04180d79442becf9d. The texture was considered as metadata and not a point property and so the wrong signal was fired. 

> We must also verify if textures are automatically removed from DEMs when the underlying image is removed from the project.

This works.

On another note I think that the method that we use to "refresh" entities is redundant. Pyvista already substitutes entities with the same name so It is not necessary to remove the actor and replace it with a new one (see #33).
